# -*- coding: utf-8 -*-
"""Data Collection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JqtJ1spax7wRUWlNW7UVXrzHHr8I2jGS
"""

import tweepy
import pandas as pd

def get_api():
    api_key = '8RQ5xPiDzAg1duMVpj9pWYEdX'
    api_key_secret = 'BqfcElqH5G6yAFHafuMQWO5ljp8Bosa402DzldWgc3mzCOSrSB'
    access_token = '1570146620653850629-erndFgwUuLXuK8prEhhrpkqlBUICih'
    access_token_secret = 'hwjy8IzsfECPVje0SAzdg3YorFifjAZbpBBgmLxBxnGVc'
    auth = tweepy.OAuthHandler(api_key, api_key_secret)
    auth.set_access_token(access_token, access_token_secret)
    return tweepy.API(auth,wait_on_rate_limit=True)

cols=['screenName','description','location','text']

def collect_User_TimelineData(username,start_date,end_date):
  api = get_api()
  db = pd.DataFrame(columns=cols, dtype=object)
  for tweet in tweepy.Cursor(api.user_timeline, screen_name=username, since=start_date,until=end_date,tweet_mode='extended').items(10000):
      username = tweet.user.screen_name
      description = tweet.user.description
      location = tweet.user.location
      tweet_text = tweet.full_text
      ith_tweet = [username, description,
              location, tweet_text]
      db.loc[len(db)] = ith_tweet
  return db

dates=[('2012-01-01','2012-12-31'),('2013-01-01','2013-12-31'),('2014-01-01','2014-12-31'),('2015-01-01','2015-12-31'),('2016-01-01','2016-12-31'),('2017-01-01','2017-12-31'),('2018-01-01','2018-12-31'),('2019-01-01','2019-12-31'),('2020-01-01','2020-12-31'),('2021-01-01','2021-12-31'),('2022-01-01','2022-11-01')]

df= pd.DataFrame(columns=cols, dtype=object)
for x in dates:
  df=df.append(collect_User_TimelineData('CNN',x[0],x[1]),ignore_index=True)

df.to_csv('./data/CNN_1000_data_with_dates2.csv')

df.shape

df_fox= pd.DataFrame(columns=cols, dtype=object)
for x in dates:
  df_fox=df_fox.append(collect_User_TimelineData('FoxNews',x[0],x[1]),ignore_index=True)

df_fox.to_csv('./data/FOX_NEWS_1000_data_with_dates2.csv')

df_fox.shape

df_Reuters= pd.DataFrame(columns=cols, dtype=object)
for x in dates:
  df_Reuters=df_Reuters.append(collect_User_TimelineData('Reuters',x[0],x[1]),ignore_index=True)

df_Reuters.to_csv('./data/Reuters_1000_data_with_dates2.csv')

df_Reuters.shape